#!/usr/bin/env python3

import gevent.monkey
gevent.monkey.patch_all()  # noqa

import logging
import sys

from contestro import ConfigError, default_argument_parser
from contestro.service.LogService import LogService


logger = logging.getLogger(__name__)


def main():
    success = default_argument_parser('Logger for Contestro.',
                                      LogService).run()
    return 0 if success is True else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ConfigError as error:
        logger.critical(error)
        sys.exit(1)
